# Generated by Django 6.0.5 on 2026-05-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('sales_rep', 'Sales Rep'), ('accounts_manager', 'Accounts Manager'), ('management', 'Management'), ('warehouse_officer', 'Warehouse Officer'), ('logistics_officer', 'Logistics Officer')], max_length=50),
        ),
    ]
