# Generated by Django 6.0.5 on 2026-05-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='movement_type',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='quantity',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_changed',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
