# Generated by Django 6.0.5 on 2026-05-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accounts_approved', 'Accounts Approved'), ('management_approved', 'Management Approved'), ('warehouse_processing', 'Warehouse Processing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='submitted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
