# Generated by Django 6.0.5 on 2026-05-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderworkflow',
            name='created_at',
        ),
        migrations.AddField(
            model_name='orderworkflow',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderworkflow',
            name='product',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orderworkflow',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('accounts_approved', 'Accounts Approved'), ('management_approved', 'Management Approved'), ('warehouse_processing', 'Warehouse Processing'), ('dispatched', 'Dispatched')], default='submitted', max_length=50),
        ),
    ]
