# Generated by Django 6.0.5 on 2026-05-18 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_remove_orderworkflow_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderworkflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
